Document: sama5d2-utils
Title: Debian sama5d2-utils Manual
Author: <insert document author here>
Abstract: This manual describes what sama5d2-utils is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sama5d2-utils/sama5d2-utils.sgml.gz

Format: postscript
Files: /usr/share/doc/sama5d2-utils/sama5d2-utils.ps.gz

Format: text
Files: /usr/share/doc/sama5d2-utils/sama5d2-utils.text.gz

Format: HTML
Index: /usr/share/doc/sama5d2-utils/html/index.html
Files: /usr/share/doc/sama5d2-utils/html/*.html
